server:
  port: 10087
spring:
  application:
    name: anxinpha-registry
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10087/eureka/
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 10000