server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10087/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
spring:
  application:
    name: upload-service
  jackson:
    default-property-inclusion: non_empty
fdfs:
  so-timeout: 1501 # 超时时间
  connect-timeout: 601 # 连接超时时间
  thumb-image: # 缩略图
    width: 80
    height: 80
  tracker-list: # tracker地址：你的虚拟机服务器地址+端口（默认是22122）
    - 192.168.112.128:22122
