server:
  port: 10010
spring:
  application:
    name: anxinpha-gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10087/eureka/
    registry-fetch-interval-seconds: 5
zuul:
  prefix: /api
  routes:
    item-service:
      path: /item/**
    user-service:
      path: /user/**
    auth-service:
      path: /auth/**
  host:
    connect-timeout-millis: 15000 #HTTP连接超时要比Hystrix的大
    socket-timeout-millis: 60000   #socket超时
  add-host-header: true
  sensitive-headers:
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
